export const COUNTRY_DATA = [
  {index: 1, name: 'AFGHANISTAN', code: '93'},
  {index: 2, name: 'ALASKA (USA)', code: '1-907'},
  {index: 3, name: 'ALBANIA', code: '355'},
  {index: 4, name: 'ALGERIA', code: '213'},
  {index: 5, name: 'AMERICAN SAMOA', code: '1-684'},
  {index: 6, name: 'ANDORRA', code: '376'},
  {index: 7, name: 'ANGOLA', code: '244'},
  {index: 8, name: 'ANGUILLA', code: '1-264'},
  {index: 9, name: 'ANTIGUA & BARBUDA', code: '1-268'},
  {index: 10, name: 'ARGENTINA', code: '54'},
  {index: 11, name: 'ARMENIA', code: '374'},
  {index: 12, name: 'ARUBA', code: '297'},
  {index: 13, name: 'ASCENSION', code: '247'},
  {index: 14, name: 'AUSTRALIA', code: '61'},
  {index: 15, name: 'AUSTRIA', code: '43'},
  {index: 16, name: 'AZERBAIJAN', code: '994'},
  {index: 17, name: 'BAHAMAS', code: '1-242'},
  {index: 18, name: 'BAHRAIN', code: '973'},
  {index: 19, name: 'BANGLADESH', code: '880'},
  {index: 20, name: 'BARBADOS', code: '1-246'},
  {index: 21, name: 'BELARUS', code: '375'},
  {index: 22, name: 'BELGIUM', code: '32'},
  {index: 23, name: 'BELIZE', code: '501'},
  {index: 24, name: 'BENIN', code: '229'},
  {index: 25, name: 'BERMUDA', code: '1-441'},
  {index: 26, name: 'BHUTAN', code: '975'},
  {index: 27, name: 'BOLIVIA', code: '591'},
  {index: 28, name: 'BOSNIA / HERZEGOVINA', code: '387'},
  {index: 29, name: 'BOTSWANA', code: '267'},
  {index: 30, name: 'BRAZIL', code: '55'},
  {index: 31, name: 'BRITISH VIRGINISLANDS', code: '1-284'},
  {index: 32, name: 'BRUNEI', code: '673'},
  {index: 33, name: 'BULGARIA', code: '359'},
  {index: 34, name: 'BURKINA FASO', code: '226'},
  {index: 35, name: 'BURUNDI', code: '257'},
  {index: 36, name: 'CAMBODIA', code: '855'},
  {index: 37, name: 'CAMEROON', code: '237'},
  {index: 38, name: 'CANADA', code: '1'},
  {index: 39, name: 'CAPE VERDE', code: '238'},
  {index: 40, name: 'CAYMAN ISLANDS', code: '1-345'},
  {index: 41, name: 'CENTRAL AFRICANREPUBLIC', code: '236'},
  {index: 42, name: 'CHAD', code: '235'},
  {index: 43, name: 'CHILE', code: '56'},
  {index: 44, name: 'CHINA', code: '86'},
  {index: 45, name: 'COLOMBIA', code: '57'},
  {index: 46, name: 'COMOROS', code: '269'},
  {index: 47, name: 'CONGO', code: '242'},
  {index: 48, name: 'CONGO DEM. REP.(ZAIRE)', code: '243'},
  {index: 49, name: 'COOK ISLAND', code: '682'},
  {index: 50, name: 'COSTA RICA', code: '506'},
  {index: 51, name: 'CROATIA', code: '385'},
  {index: 52, name: 'CUBA', code: '53'},
  {index: 53, name: 'CYPRUS', code: '357'},
  {index: 54, name: 'CZECH REPUBLIC', code: '420'},
  {index: 55, name: 'DENMARK', code: '45'},
  {index: 56, name: 'DIEGO GARCIA', code: '246'},
  {index: 57, name: 'DJIBOUTI', code: '253'},
  {index: 58, name: 'DOMINICA', code: '1-767'},
  {index: 59, name: 'DOMINICAN REPUBLIC', code: '1-809'},
  {index: 60, name: 'EAST TIMOR', code: '670'},
  {index: 61, name: 'ECUADOR', code: '593'},
  {index: 62, name: 'EGYPT', code: '20'},
  {index: 63, name: 'EL SALVADOR', code: '503'},
  {index: 64, name: 'EQUATORIAL GUINEA', code: '240'},
  {index: 65, name: 'ERITREA', code: '291'},
  {index: 66, name: 'ESTONIA', code: '372'},
  {index: 67, name: 'ETHIOPIA', code: '251'},
  {index: 68, name: 'FALKLAND ISLANDS', code: '500'},
  {index: 69, name: 'FAROE ISLANDS', code: '298'},
  {index: 70, name: 'FIJI', code: '679'},
  {index: 71, name: 'FINLAND', code: '358'},
  {index: 72, name: 'FRANCE', code: '33'},
  {index: 73, name: 'FRENCH GUIANA', code: '594'},
  {index: 74, name: 'FRENCH POLYNESIA', code: '689'},
  {index: 75, name: 'GABON', code: '241'},
  {index: 76, name: 'GAMBIA', code: '220'},
  {index: 77, name: 'GEORGIA', code: '995'},
  {index: 78, name: 'GERMANY', code: '49'},
  {index: 79, name: 'GHANA', code: '233'},
  {index: 80, name: 'GIBRALTAR', code: '350'},
  {index: 81, name: 'GREECE', code: '30'},
  {index: 82, name: 'GREENLAND', code: '299'},
  {index: 83, name: 'GRENADA', code: '1-473'},
  {index: 84, name: 'GUADALOUPE', code: '590'},
  {index: 85, name: 'GUAM', code: '1-671'},
  {index: 86, name: 'GUATEMALA', code: '502'},
  {index: 87, name: 'GUINEA', code: '224'},
  {index: 88, name: 'GUINEA BISSAU', code: '245'},
  {index: 89, name: 'GUYANA', code: '592'},
  {index: 90, name: 'HAITI', code: '509'},
  {index: 91, name: 'HAWAII (USA)', code: '1-808'},
  {index: 92, name: 'HONDURAS', code: '504'},
  {index: 93, name: 'HONG KONG', code: '852'},
  {index: 94, name: 'HUNGARY', code: '36'},
  {index: 95, name: 'ICELAND', code: '354'},
  {index: 96, name: 'INDIA', code: '91'},
  {index: 97, name: 'INDONESIA', code: '62'},
  {index: 98, name: 'IRAN', code: '98'},
  {index: 99, name: 'IRAQ', code: '964'},
  {index: 100, name: 'IRELAND', code: '353'},
  {index: 101, name: 'ISRAEL', code: '972'},
  {index: 102, name: 'ITALY', code: '39'},
  {index: 103, name: 'IVORY COAST', code: '225'},
  {index: 104, name: 'JAMAICA', code: '1-876'},
  {index: 105, name: 'JAPAN', code: '81'},
  {index: 106, name: 'JORDAN', code: '962'},
  {index: 107, name: 'KAZAKHSTAN', code: '7'},
  {index: 108, name: 'KENYA', code: '254'},
  {index: 109, name: 'KIRIBATI', code: '686'},
  {index: 110, name: 'KOREA (NORTH)', code: '850'},
  {index: 111, name: 'KOREA SOUTH', code: '82'},
  {index: 112, name: 'KUWAIT', code: '965'},
  {index: 113, name: 'KYRGHYZSTAN', code: '996'},
  {index: 114, name: 'LAOS', code: '856'},
  {index: 115, name: 'LATVIA', code: '371'},
  {index: 116, name: 'LEBANON', code: '961'},
  {index: 117, name: 'LESOTHO', code: '266'},
  {index: 118, name: 'LIBERIA', code: '231'},
  {index: 119, name: 'LIBYA', code: '218'},
  {index: 120, name: 'LIECHTENSTEIN', code: '423'},
  {index: 121, name: 'LITHUANIA', code: '370'},
  {index: 122, name: 'LUXEMBOURG', code: '352'},
  {index: 123, name: 'MACAU', code: '853'},
  {index: 124, name: 'MACEDONIA', code: '389'},
  {index: 125, name: 'MADAGASCAR', code: '261'},
  {index: 126, name: 'MALAWI', code: '265'},
  {index: 127, name: 'MALAYSIA', code: '60'},
  {index: 128, name: 'MALDIVES', code: '960'},
  {index: 129, name: 'MALI', code: '223'},
  {index: 130, name: 'MALTA', code: '356'},
  {index: 131, name: 'MARIANA IS.(SAIPAN)', code: '1-670'},
  {index: 132, name: 'MARSHALL ISLANDS', code: '692'},
  {index: 133, name: 'MARTINIQUE(FRENCHANTILLES)', code: '596'},
  {index: 134, name: 'MAURITANIA', code: '222'},
  {index: 135, name: 'MAURITIUS', code: '230'},
  {index: 136, name: 'MAYOTTE', code: '269'},
  {index: 137, name: 'MEXICO', code: '52'},
  {index: 138, name: 'MICRONESIA', code: '691'},
  {index: 139, name: 'MOLDOVA', code: '373'},
  {index: 140, name: 'MONACO', code: '377'},
  {index: 141, name: 'MONGOLIA', code: '976'},
  {index: 142, name: 'MONTSERRAT', code: '1-664 '},
  {index: 143, name: 'MOROCCO', code: '212'},
  {index: 144, name: 'MOZAMBIQUE', code: '258'},
  {index: 145, name: 'MYANMAR', code: '95'},
  {index: 146, name: 'NAMIBIA', code: '264'},
  {index: 147, name: 'NAURU', code: '674'},
  {index: 148, name: 'NEPAL', code: '977'},
  {index: 149, name: 'NETHERLANDS', code: '31'},
  {index: 150, name: 'NETHERLANDS ANTILLES', code: '599'},
  {index: 151, name: 'NEW CALEDONIA', code: '687'},
  {index: 152, name: 'NEW ZEALAND', code: '64'},
  {index: 153, name: 'NICARAGUA', code: '505'},
  {index: 154, name: 'NIGER', code: '227'},
  {index: 155, name: 'NIGERIA', code: '234'},
  {index: 156, name: 'NIUE ISLAND', code: '683'},
  {index: 157, name: 'NORWAY', code: '47'},
  {index: 158, name: 'OMAN', code: '968'},
  {index: 159, name: 'PAKISTAN', code: '92'},
  {index: 160, name: 'PALAU', code: '680'},
  {index: 161, name: 'PALESTINE', code: '970'},
  {index: 162, name: 'PANAMA', code: '507'},
  {index: 163, name: 'PAPUA NEW GUINEA', code: '675'},
  {index: 164, name: 'PARAGUAY', code: '595'},
  {index: 165, name: 'PERU', code: '51'},
  {index: 166, name: 'PHILIPPINES', code: '63'},
  {index: 167, name: 'POLAND', code: '48'},
  {index: 168, name: 'PORTUGAL', code: '351'},
  {index: 169, name: 'PUERTO RICO (I) (USA)', code: '1-787'},
  {index: 170, name: 'PUERTO RICO (II)(USA)', code: '1-939'},
  {index: 171, name: 'QATAR', code: '974'},
  {index: 172, name: 'REUNION', code: '262'},
  {index: 173, name: 'ROMANIA', code: '40'},
  {index: 174, name: 'RUSSIA', code: '7'},
  {index: 175, name: 'RWANDA', code: '250'},
  {index: 176, name: 'SAMOA WESTERN', code: '685'},
  {index: 177, name: 'SAN MARINO', code: '378'},
  {index: 178, name: 'SAO TOME &PRINCIPE', code: '239'},
  {index: 179, name: 'SAUDI ARABIA', code: '966'},
  {index: 180, name: 'SENEGAL', code: '221'},
  {index: 181, name: 'SEYCHELLES', code: '248'},
  {index: 182, name: 'SIERRA LEONE', code: '232'},
  {index: 183, name: 'SINGAPORE', code: '65'},
  {index: 184, name: 'SLOVAKIA', code: '421'},
  {index: 185, name: 'SLOVENIA', code: '386'},
  {index: 186, name: 'SOLOMON ISLANDS', code: '677'},
  {index: 187, name: 'SOMALIA', code: '252'},
  {index: 188, name: 'SOUTH AFRICA', code: '27'},
  {index: 189, name: 'SPAIN', code: '34'},
  {index: 190, name: 'SRI LANKA', code: '94'},
  {index: 191, name: 'ST HELENA', code: '290'},
  {index: 192, name: 'ST KITTS & NEVIS', code: '1-869 '},
  {index: 193, name: 'ST LUCIA', code: '1-758 '},
  {index: 194, name: 'ST VINCENT &GRENADINES', code: '1-784 '},
  {index: 195, name: 'ST. PIERRE &MIQUELON', code: '508'},
  {index: 196, name: 'SUDAN', code: '249'},
  {index: 197, name: 'SURINAM', code: '597'},
  {index: 198, name: 'SWAZILAND', code: '268'},
  {index: 199, name: 'SWEDEN', code: '46'},
  {index: 200, name: 'SWITZERLAND', code: '41'},
  {index: 201, name: 'SYRIA', code: '963'},
  {index: 202, name: 'TAIWAN', code: '886'},
  {index: 203, name: 'TAJIKISTAN', code: '992'},
  {index: 204, name: 'TANZANIA', code: '255'},
  {index: 205, name: 'THAILAND', code: '66'},
  {index: 206, name: 'TOGO', code: '228'},
  {index: 207, name: 'TOKELAU', code: '690'},
  {index: 208, name: 'TONGA', code: '676'},
  {index: 209, name: 'TRINIDAD & TOBAGO', code: '1-868'},
  {index: 210, name: 'TUNISIA', code: '216'},
  {index: 211, name: 'TURKEY', code: '90'},
  {index: 212, name: 'TURKMENISTAN', code: '993'},
  {index: 213, name: 'TURKS & CAICOSISLANDS', code: '1-649 '},
  {index: 214, name: 'TUVALU', code: '688'},
  {index: 215, name: 'UGANDA', code: '256'},
  {index: 216, name: 'UKRAINE', code: '380'},
  {index: 217, name: 'UNITED ARAB EMIRATES', code: '971'},
  {index: 218, name: 'UNITED KINGDOM', code: '44'},
  {index: 219, name: 'URUGUAY', code: '598'},
  {index: 220, name: 'UZBEKISTAN', code: '998'},
  {index: 221, name: 'VANUATU', code: '678'},
  {index: 222, name: 'VATICAN CITY', code: '39'},
  {index: 223, name: 'VENEZUELA', code: '58'},
  {index: 224, name: 'VIETNAM', code: '84'},
  {index: 225, name: 'VIRGIN ISLAND (USA)', code: '1-340'},
  {index: 226, name: 'WALLIS & FUTUNA', code: '681'},
  {index: 227, name: 'YEMEN', code: '967'},
  {index: 228, name: 'YUGOSLAVIA (SERBIA)', code: '381'},
  {index: 229, name: 'ZAMBIA', code: '260'},
  {index: 230, name: 'ZANZIBAR', code: '255'},
  {index: 231, name: 'ZIMBABWE', code: '263'},
];

export const COUNTRIES = [
  {name: 'Albania'},
  {name: 'Algeria'},
  {name: 'Andorra'},
  {name: 'Angola'},
  {name: 'Antigua & Deps'},
  {name: 'Argentina'},
  {name: 'Armenia'},
  {name: 'Australia'},
  {name: 'Austria'},
  {name: 'Azerbaijan'},
  {name: 'Bahamas'},
  {name: 'Bahrain'},
  {name: 'Bangladesh'},
  {name: 'Barbados'},
  {name: 'Belarus'},
  {name: 'Belgium'},
  {name: 'Belize'},
  {name: 'Benin'},
  {name: 'Bhutan'},
  {name: 'Bolivia'},
  {name: 'Bosnia Herzegovina'},
  {name: 'Botswana'},
  {name: 'Brazil'},
  {name: 'Brunei'},
  {name: 'Bulgaria'},
  {name: 'Burkina'},
  {name: 'Burundi'},
  {name: 'Cambodia'},
  {name: 'Cameroon'},
  {name: 'Canada'},
  {name: 'Cape Verde'},
  {name: 'Central African Rep'},
  {name: 'Chad'},
  {name: 'Chile'},
  {name: 'China'},
  {name: 'Colombia'},
  {name: 'Comoros'},
  {name: 'Congo'},
  {name: 'Congo {Democratic Rep}'},
  {name: 'Costa Rica'},
  {name: 'Croatia'},
  {name: 'Cuba'},
  {name: 'Cyprus'},
  {name: 'Czech Republic'},
  {name: 'Denmark'},
  {name: 'Djibouti'},
  {name: 'Dominica'},
  {name: 'Dominican Republic'},
  {name: 'East Timor'},
  {name: 'Ecuador'},
  {name: 'Egypt'},
  {name: 'El Salvador'},
  {name: 'Equatorial Guinea'},
  {name: 'Eritrea'},
  {name: 'Estonia'},
  {name: 'Ethiopia'},
  {name: 'Fiji'},
  {name: 'Finland'},
  {name: 'France'},
  {name: 'Gabon'},
  {name: 'Gambia'},
  {name: 'Georgia'},
  {name: 'Germany'},
  {name: 'Ghana'},
  {name: 'Greece'},
  {name: 'Grenada'},
  {name: 'Guatemala'},
  {name: 'Guinea'},
  {name: 'Guinea-Bissau'},
  {name: 'Guyana'},
  {name: 'Haiti'},
  {name: 'Honduras'},
  {name: 'Hungary'},
  {name: 'Iceland'},
  {name: 'India'},
  {name: 'Indonesia'},
  {name: 'Iran'},
  {name: 'Iraq'},
  {name: 'Ireland {Republic}'},
  {name: 'Israel'},
  {name: 'Italy'},
  {name: 'Ivory Coast'},
  {name: 'Jamaica'},
  {name: 'Japan'},
  {name: 'Jordan'},
  {name: 'Kazakhstan'},
  {name: 'Kenya'},
  {name: 'Kiribati'},
  {name: 'Korea North'},
  {name: 'Korea South'},
  {name: 'Kosovo'},
  {name: 'Kuwait'},
  {name: 'Kyrgyzstan'},
  {name: 'Laos'},
  {name: 'Latvia'},
  {name: 'Lebanon'},
  {name: 'Lesotho'},
  {name: 'Liberia'},
  {name: 'Libya'},
  {name: 'Liechtenstein'},
  {name: 'Lithuania'},
  {name: 'Luxembourg'},
  {name: 'Macedonia'},
  {name: 'Madagascar'},
  {name: 'Malawi'},
  {name: 'Malaysia'},
  {name: 'Maldives'},
  {name: 'Mali'},
  {name: 'Malta'},
  {name: 'Marshall Islands'},
  {name: 'Mauritania'},
  {name: 'Mauritius'},
  {name: 'Mexico'},
  {name: 'Micronesia'},
  {name: 'Moldova'},
  {name: 'Monaco'},
  {name: 'Mongolia'},
  {name: 'Montenegro'},
  {name: 'Morocco'},
  {name: 'Mozambique'},
  {name: 'Myanmar, {Burma}'},
  {name: 'Namibia'},
  {name: 'Nauru'},
  {name: 'Nepal'},
  {name: 'Netherlands'},
  {name: 'New Zealand'},
  {name: 'Nicaragua'},
  {name: 'Niger'},
  {name: 'Nigeria'},
  {name: 'Norway'},
  {name: 'Oman'},
  {name: 'Pakistan'},
  {name: 'Palau'},
  {name: 'Panama'},
  {name: 'Papua New Guinea'},
  {name: 'Paraguay'},
  {name: 'Peru'},
  {name: 'Philippines'},
  {name: 'Poland'},
  {name: 'Portugal'},
  {name: 'Qatar'},
  {name: 'Romania'},
  {name: 'Russian Federation'},
  {name: 'Rwanda'},
  {name: 'St Kitts & Nevis'},
  {name: 'St Lucia'},
  {name: 'Samoa'},
  {name: 'San Marino'},
  {name: 'Sao Tome & Principe'},
  {name: 'Saudi Arabia'},
  {name: 'Senegal'},
  {name: 'Serbia'},
  {name: 'Seychelles'},
  {name: 'Sierra Leone'},
  {name: 'Singapore'},
  {name: 'Slovakia'},
  {name: 'Slovenia'},
  {name: 'Solomon Islands'},
  {name: 'Somalia'},
  {name: 'South Africa'},
  {name: 'South Sudan'},
  {name: 'Spain'},
  {name: 'Sri Lanka'},
  {name: 'Sudan'},
  {name: 'Suriname'},
  {name: 'Swaziland'},
  {name: 'Sweden'},
  {name: 'Switzerland'},
  {name: 'Syria'},
  {name: 'Taiwan'},
  {name: 'Tajikistan'},
  {name: 'Tanzania'},
  {name: 'Thailand'},
  {name: 'Togo'},
  {name: 'Tonga'},
  {name: 'Trinidad & Tobago'},
  {name: 'Tunisia'},
  {name: 'Turkey'},
  {name: 'Turkmenistan'},
  {name: 'Tuvalu'},
  {name: 'Uganda'},
  {name: 'Ukraine'},
  {name: 'United Arab Emirates'},
  {name: 'United Kingdom'},
  {name: 'United States'},
  {name: 'Uruguay'},
  {name: 'Uzbekistan'},
  {name: 'Vanuatu'},
  {name: 'Vatican City'},
  {name: 'Venezuela'},
  {name: 'Vietnam'},
  {name: 'Yemen'},
  {name: 'Zambia'},
  {name: 'Zimbabwe'},
];

export const DEPARTMENTS = [
  {name: 'B.Tech - Chemical Engineering'},
  {name: 'B.Tech - Civil Engineering'},
  {name: 'B.Tech - Computer Science and Engineering'},
  {name: 'B.Tech - Electrical and Electronics Engineering'},
  {name: 'B.Tech - Electronics and Communication Engineering'},
  {name: 'B.Tech - Instrumentation and Control Engineering'},
  {name: 'B.Tech - Mechanical Engineering'},
  {name: 'B.Tech - Metallurgical and Materials Engineering'},
  {name: 'B.Tech - Production Engineering'},

  {name: 'B.Arch - Architecture'},

  {name: 'M.Tech - Energy Engineering'},
  {name: 'M.Tech - Chemical Engineering'},
  {name: 'M.Tech - Process Control and Instrumentation'},
  {name: 'M.Tech - Industrial Automation'},
  {name: 'M.Tech - Transportation Engineering and Management'},
  {name: 'M.Tech - Construction Technology and Management'},
  {name: 'M.Tech - Structural Engineering'},
  {name: 'M.Tech - Environmental Engineering'},
  {name: 'M.Tech - Computer Science and Engineering'},
  {name: 'M.Tech - Power Electronics'},
  {name: 'M.Tech - Power Systems'},
  {name: 'M.Tech - Communication Systems'},
  {name: 'M.Tech - VLSI System'},
  {name: 'M.Tech - Industrial Safety Engineering'},
  {name: 'M.Tech - Thermal Power Engineering'},
  {name: 'M.Tech - Material science and Engineering'},
  {name: 'M.Tech - Welding Engineering'},
  {name: 'M.Tech - Industrial Engineering and Management'},
  {name: 'M.Tech - Manufacturing Technology'},
  {name: 'M.Tech - Non-Destructive Testing'},
  {name: 'M.Tech - Data Analytics'},
  {name: 'M.Tech - Geotechnical Engineering'},
  {name: 'M.Tech - Master of Architecture'},
  {name: 'M.Tech - Energy Efficient and Sustainable Architecture'},
  {name: 'M.Tech - Master of Science'},
  {name: 'M.Tech - Computer Science'},
  {name: 'M.Tech - Chemistry'},
  {name: 'M.Tech - Physics'},
  {name: 'M.Tech - Mathematics'},
  {name: 'M.Tech - Master of Business Administration'},
  {name: 'M.Tech - Master of Computer Applications'},
  {name: 'M.Tech - Master of Arts'},
  {name: 'M.Tech - English (Language and Literature)'},

  {name: 'M.Sc - Chemical Engineering'},
  {name: 'M.Sc - Civil Engineering'},
  {name: 'M.Sc - Computer Science and Engineering'},
  {name: 'M.Sc - Electrical and Electronics Engineering'},
  {name: 'M.Sc - Electronics and Communication Engineering'},
  {name: 'M.Sc - Instrumentation and Control Engineering'},
  {name: 'M.Sc - Mechanical Engineering'},
  {name: 'M.Sc - Metallurgical and Materials Engineering'},
  {name: 'M.Sc - Production Engineering'},

  {name: 'Ph.D - Chemical Engineering'},
  {name: 'Ph.D - Civil Engineering'},
  {name: 'Ph.D - Computer Science and Engineering'},
  {name: 'Ph.D - Electrical and Electronics Engineering'},
  {name: 'Ph.D - Electronics and Communication Engineering'},
  {name: 'Ph.D - Instrumentation and Control Engineering'},
  {name: 'Ph.D - Mechanical Engineering'},
  {name: 'Ph.D - Metallurgical and Materials Engineering'},
  {name: 'Ph.D - Production Engineering'},
  {name: 'Ph.D - Architecture'},
  {name: 'Ph.D - Chemistry'},
  {name: 'Ph.D - Computer Applications'},
  {name: 'Ph.D - Humanities'},
  {name: 'Ph.D - Energy and Environment'},
  {name: 'Ph.D - Management Studies'},
  {name: 'Ph.D - Mathematics'},
  {name: 'Ph.D - Physics'},
];

export const Gender = [
  {
    name: 'male',
  },
  {
    name: 'female',
  },
];

export const MODAL_TYPE_CODE = 0;
export const MODAL_TYPE_NATIONALITY = 1;
export const MODAL_TYPE_GENDER = 2;
export const MODAL_TYPE_DEPARTMENT = 3;
